version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "this is the build job"
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
